package com.amena.backend.controller.impl;

import com.amena.backend.api.UsersApi;
import com.amena.backend.dto.*;
import com.amena.backend.entity.User;
import com.amena.backend.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;
import com.amena.backend.exception.DuplicateEmailException;

import java.time.LocalDateTime;
import java.util.Optional;

/**
 * Implementation of the Users API generated from OpenAPI spec.
 * This controller implements the interface generated by openapi-generator.
 */
@RestController
@RequiredArgsConstructor
public class UsersApiController implements UsersApi {

    private final UserRepository userRepository;

    @Override
    public ResponseEntity<UserResponse> createUser(CreateUserRequest createUserRequest) {
        // Check if email already exists
        if (userRepository.findByEmail(createUserRequest.getEmail()).isPresent()) {
            throw new DuplicateEmailException(createUserRequest.getEmail());
        }

        User user = User.builder()
                .email(createUserRequest.getEmail())
                .firstName(createUserRequest.getFirstName())
                .lastName(createUserRequest.getLastName())
                .build();

        User savedUser = userRepository.save(user);
        return ResponseEntity.status(HttpStatus.CREATED).body(toUserResponse(savedUser));
    }

    @Override
    public ResponseEntity<Void> deleteUser(Long userId) {
        Optional<User> user = userRepository.findById(userId);
        if (user.isEmpty()) {
            return ResponseEntity.notFound().build();
        }
        userRepository.deleteById(userId);
        return ResponseEntity.noContent().build();
    }

    @Override
    public ResponseEntity<UserResponse> getUserById(Long userId) {
        return userRepository.findById(userId)
                .map(user -> ResponseEntity.ok(toUserResponse(user)))
                .orElse(ResponseEntity.notFound().build());
    }

    @Override
    public ResponseEntity<UserPage> getUsers(Integer page, Integer size) {
        Page<User> userPage = userRepository.findAll(PageRequest.of(page, size));
        return ResponseEntity.ok(toUserPage(userPage));
    }

    @Override
    public ResponseEntity<UserResponse> updateUser(Long userId, UpdateUserRequest updateUserRequest) {
        Optional<User> userOptional = userRepository.findById(userId);
        if (userOptional.isEmpty()) {
            return ResponseEntity.notFound().build();
        }

        User user = userOptional.get();
        if (updateUserRequest.getFirstName() != null) {
            user.setFirstName(updateUserRequest.getFirstName());
        }
        if (updateUserRequest.getLastName() != null) {
            user.setLastName(updateUserRequest.getLastName());
        }

        User updatedUser = userRepository.save(user);
        return ResponseEntity.ok(toUserResponse(updatedUser));
    }

    // Helper methods to convert entities to DTOs

    private UserResponse toUserResponse(User user) {
        UserResponse response = new UserResponse();
        response.setId(user.getId());
        response.setEmail(user.getEmail());
        response.setFirstName(user.getFirstName());
        response.setLastName(user.getLastName());
        response.setCreatedAt(user.getCreatedAt());
        response.setUpdatedAt(user.getUpdatedAt());
        return response;
    }

    private UserPage toUserPage(Page<User> page) {
        UserPage userPage = new UserPage();
        userPage.setContent(page.getContent().stream().map(this::toUserResponse).toList());
        userPage.setTotalElements(page.getTotalElements());
        userPage.setTotalPages(page.getTotalPages());
        userPage.setNumber(page.getNumber());
        userPage.setSize(page.getSize());
        userPage.setFirst(page.isFirst());
        userPage.setLast(page.isLast());
        userPage.setEmpty(page.isEmpty());
        return userPage;
    }
}